name: Terraform Destroy

on:
  workflow_dispatch:   # Allows manual trigger

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init (with backend)
        run: terraform init -backend-config="bucket=terraform-state-haroon-0334" -backend-config="key=vpc/terraform.tfstate" -backend-config="region=us-east-1"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
